feat: add testCpsSourceConnector
googleapis/java-pubsub-group-kafka-connector pull request #96
Opened 2022-08-31 18:15 UTC by samarthsingal

Adds an integration test for CPS source connector.

The test brings up the source connector binary, publishes to a CPS topic and consumes from the destination Kafka topic. Also adds a log4j backend for INFO logging from Kafka classes for the tests.

2022-09-13 16:16 UTC, hannahrogers-google approved these changes

2022-09-16 17:06 UTC, anguillanneuf requested changes
Thanks Samarth for adding these tests!

Missing license headers in the following files: 
- src/test/java/it/StandaloneIT.java
- src/test/java/it/Base.java

Group test/compile/provided dependencies in pom.xml. 
Place test dependencies beneath compile/provided deps in pom.xml.

2022-09-16 17:06 UTC, anguillanneuf commented on src/test/resources/kafka_vm_startup_script.sh
>  set +x
Nit: "no new line at the end of the file".

2022-09-16 17:06 UTC, anguillanneuf commented on src/test/resources/log4j.properties
> +log4j.appender.stdout.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1} - %m%n
Ditto.

2022-09-16 17:06 UTC, anguillanneuf commented on src/test/resources/pubsub-lite-sink-connector-test.properties
> +value.converter=org.apache.kafka.connect.converters.ByteArrayConverter
Ditto.

2022-09-16 17:06 UTC, anguillanneuf commented on src/test/resources/pubsub-lite-source-connector-test.properties
> +value.converter=org.apache.kafka.connect.converters.ByteArrayConverter
Ditto.

2022-09-16 17:06 UTC, anguillanneuf commented on src/test/java/it/StandaloneIT.java
> +        "org.apache.kafka.common.serialization.StringDeserializer");
A question more than a review comment, why is StringDeserializer preferred over ByteArrayDeserializer?

2022-09-16 17:06 UTC, anguillanneuf commented on src/test/java/it/StandaloneIT.java
> +          < 0) {
Could you add a comment about why the choice of using two minutes?

2022-09-16 17:06 UTC, anguillanneuf commented on src/test/java/it/StandaloneIT.java
> +      // Shut down the subscriber after 30s. Stop receiving messages.
Where was the timeout configured to be 30s?

2022-09-19 21:23 UTC, samarthsingal commented on src/test/java/it/StandaloneIT.java
> +        "org.apache.kafka.common.serialization.StringDeserializer");
We write a string message so we want to deserialize it as a string to read. Note that this is different from the key/value serializer used in the connector configs which are ByteArrayConverters so the on-disk encoding of message data in Kafka is bytes.

2022-09-19 21:25 UTC, samarthsingal commented on src/test/java/it/StandaloneIT.java
> +      // Shut down the subscriber after 30s. Stop receiving messages.
Changed to 3min.

2022-09-19 21:27 UTC, samarthsingal commented on src/test/resources/kafka_vm_startup_script.sh
>  set +x
Done.

2022-09-19 21:27 UTC, samarthsingal commented on src/test/resources/log4j.properties
> +log4j.appender.stdout.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1} - %m%n
Done.

2022-09-19 21:27 UTC, samarthsingal commented on src/test/resources/pubsub-lite-sink-connector-test.properties
> +value.converter=org.apache.kafka.connect.converters.ByteArrayConverter
Done.

2022-09-19 21:28 UTC, samarthsingal commented on src/test/resources/pubsub-lite-source-connector-test.properties
> +value.converter=org.apache.kafka.connect.converters.ByteArrayConverter
Done.

2022-09-19 21:28 UTC, samarthsingal commented on src/test/java/it/StandaloneIT.java
> +          < 0) {
Done.

2022-09-19 22:55 UTC, anguillanneuf approved these changes

2022-09-19 22:56 UTC, merged